// <auto-generated />
using System;
using Laraue.Apps.Billing.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laraue.Apps.Billing.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260905083039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.BalancePurchasedToken", b =>
                {
                    b.Property<Guid>("PaidEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paid_entity_id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.HasKey("PaidEntityId")
                        .HasName("pk_balance_purchased_tokens");

                    b.ToTable("balance_purchased_tokens", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.BalanceSubscriptionToken", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<long>("FreeTokensCount")
                        .HasColumnType("bigint")
                        .HasColumnName("free_tokens_count");

                    b.Property<long>("SubscriptionTokensCount")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_tokens_count");

                    b.HasKey("SubscriptionId")
                        .HasName("pk_balance_subscription_tokens");

                    b.ToTable("balance_subscription_tokens", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.CurrencyRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<decimal>("RateToUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("rate_to_usd");

                    b.HasKey("Id")
                        .HasName("pk_currency_rates");

                    b.ToTable("currency_rates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3f15a99-c08e-420c-9aca-8bd35a13b4ec"),
                            Code = "USD",
                            RateToUsd = 1m
                        },
                        new
                        {
                            Id = new Guid("d8b3db18-09f8-4cd8-b4b8-c6d4402e2292"),
                            Code = "RUB",
                            RateToUsd = 0.012m
                        });
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.LaraueBoardsPersonalTariff", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("LimitFreeTeamOrganizationsCount")
                        .HasColumnType("integer")
                        .HasColumnName("limit_free_team_organizations_count");

                    b.Property<int?>("LimitIssuesPerMonth")
                        .HasColumnType("integer")
                        .HasColumnName("limit_issues_per_month");

                    b.HasKey("Id")
                        .HasName("pk_laraue_boards_personal_tariffs");

                    b.ToTable("laraue_boards_personal_tariffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            LimitFreeTeamOrganizationsCount = 1,
                            LimitIssuesPerMonth = 500
                        },
                        new
                        {
                            Id = 1,
                            LimitIssuesPerMonth = 50000
                        });
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.LaraueBoardsTeamTariff", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("LimitIssuesPerMonth")
                        .HasColumnType("integer")
                        .HasColumnName("limit_issues_per_month");

                    b.HasKey("Id")
                        .HasName("pk_laraue_boards_team_tariffs");

                    b.ToTable("laraue_boards_team_tariffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            LimitIssuesPerMonth = 500
                        },
                        new
                        {
                            Id = 3,
                            LimitIssuesPerMonth = 50000
                        },
                        new
                        {
                            Id = 4,
                            LimitIssuesPerMonth = 200000
                        });
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.MarkdownTranslatorPersonalTariff", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("IncludedDailyFreeTokensCount")
                        .HasColumnType("bigint")
                        .HasColumnName("included_daily_free_tokens_count");

                    b.HasKey("Id")
                        .HasName("pk_markdown_translator_personal_tariffs");

                    b.ToTable("markdown_translator_personal_tariffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 5,
                            IncludedDailyFreeTokensCount = 10000L
                        },
                        new
                        {
                            Id = 6,
                            IncludedDailyFreeTokensCount = 10000L
                        },
                        new
                        {
                            Id = 7,
                            IncludedDailyFreeTokensCount = 10000L
                        });
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.PurchasedTokenPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid>("PaidEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_entity_id");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<Guid>("TokenPackId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_pack_id");

                    b.HasKey("Id")
                        .HasName("pk_purchased_token_packs");

                    b.HasIndex("TokenPackId")
                        .HasDatabaseName("ix_purchased_token_packs_token_pack_id");

                    b.ToTable("purchased_token_packs", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "laraue_boards",
                            Name = "Laraue Boards"
                        },
                        new
                        {
                            Id = 2,
                            Code = "markdown_translator",
                            Name = "Markdown Translator"
                        });
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CurrentPeriodFinishesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_finishes_at");

                    b.Property<DateTime>("CurrentPeriodStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_started_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PaidEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_entity_id");

                    b.Property<int?>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer")
                        .HasColumnName("tariff_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_subscriptions_service_id");

                    b.HasIndex("TariffId")
                        .HasDatabaseName("ix_subscriptions_tariff_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("billing_period");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<long>("IncludedTokensCount")
                        .HasColumnType("bigint")
                        .HasColumnName("included_tokens_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.ToTable("tariffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            BillingPeriod = 0,
                            Code = "personal_free",
                            IncludedTokensCount = 0L,
                            IsActive = true,
                            Price = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 1,
                            BillingPeriod = 0,
                            Code = "personal_plus",
                            IncludedTokensCount = 300000L,
                            IsActive = true,
                            Price = 400,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            BillingPeriod = 0,
                            Code = "team_free",
                            IncludedTokensCount = 0L,
                            IsActive = true,
                            Price = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            BillingPeriod = 0,
                            Code = "team",
                            IncludedTokensCount = 750000L,
                            IsActive = true,
                            Price = 600,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            BillingPeriod = 0,
                            Code = "team_business",
                            IncludedTokensCount = 2500000L,
                            IsActive = true,
                            Price = 1400,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            BillingPeriod = 0,
                            Code = "free",
                            IncludedTokensCount = 0L,
                            IsActive = true,
                            Price = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            BillingPeriod = 0,
                            Code = "plus",
                            IncludedTokensCount = 300000L,
                            IsActive = true,
                            Price = 400,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            BillingPeriod = 0,
                            Code = "pro",
                            IncludedTokensCount = 1200000L,
                            IsActive = true,
                            Price = 1000,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<TimeSpan>("ExpirationDuration")
                        .HasColumnType("interval")
                        .HasColumnName("expiration_duration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<long>("TokensCount")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_count");

                    b.HasKey("Id")
                        .HasName("pk_token_packs");

                    b.ToTable("token_packs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("76abd692-c450-4cd6-80e4-b9c012d91610"),
                            Code = "small",
                            ExpirationDuration = new TimeSpan(0, 0, 0, 0, 0),
                            IsActive = true,
                            Price = 300,
                            TokensCount = 100000L
                        },
                        new
                        {
                            Id = new Guid("bb76c6c6-41b9-4546-972a-a9730456fdf0"),
                            Code = "medium",
                            ExpirationDuration = new TimeSpan(0, 0, 0, 0, 0),
                            IsActive = true,
                            Price = 1200,
                            TokensCount = 600000L
                        },
                        new
                        {
                            Id = new Guid("2a840fe4-175a-4e69-834e-5f5f6c5e2150"),
                            Code = "large",
                            ExpirationDuration = new TimeSpan(0, 0, 0, 0, 0),
                            IsActive = true,
                            Price = 4000,
                            TokensCount = 3000000L
                        });
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Delta")
                        .HasColumnType("bigint")
                        .HasColumnName("delta");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PaidEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_entity_id");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionTokensSpentId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_tokens_spent_id");

                    b.HasKey("Id")
                        .HasName("pk_token_transactions");

                    b.HasIndex("SubscriptionTokensSpentId")
                        .HasDatabaseName("ix_token_transactions_subscription_tokens_spent_id");

                    b.ToTable("token_transactions", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenTransactionPurchasedTokenPack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("ChargedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("charged_amount");

                    b.Property<Guid>("PurchasedTokenPackId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchased_token_pack_id");

                    b.Property<Guid?>("TokenTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_token_transaction_purchased_token_packs");

                    b.HasIndex("PurchasedTokenPackId")
                        .HasDatabaseName("ix_token_transaction_purchased_token_packs_purchased_token_pac");

                    b.HasIndex("TokenTransactionId")
                        .HasDatabaseName("ix_token_transaction_purchased_token_packs_token_transaction_id");

                    b.ToTable("token_transaction_purchased_token_packs", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenTransactionSubscriptionTokenPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ChargedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("charged_amount");

                    b.Property<long?>("ChargedFreeAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("charged_free_amount");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_token_transaction_subscription_token_packs");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_token_transaction_subscription_token_packs_subscription_id");

                    b.ToTable("token_transaction_subscription_token_packs", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.PurchasedTokenPack", b =>
                {
                    b.HasOne("Laraue.Apps.Billing.DataAccess.Entities.TokenPack", "TokenPack")
                        .WithMany()
                        .HasForeignKey("TokenPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchased_token_packs_token_packs_token_pack_id");

                    b.Navigation("TokenPack");
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.Subscription", b =>
                {
                    b.HasOne("Laraue.Apps.Billing.DataAccess.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_services_service_id");

                    b.HasOne("Laraue.Apps.Billing.DataAccess.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_tariffs_tariff_id");

                    b.Navigation("Service");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenTransaction", b =>
                {
                    b.HasOne("Laraue.Apps.Billing.DataAccess.Entities.TokenTransactionSubscriptionTokenPack", "SubscriptionTokensSpent")
                        .WithMany()
                        .HasForeignKey("SubscriptionTokensSpentId")
                        .HasConstraintName("fk_token_transactions_token_transaction_subscription_token_pac");

                    b.Navigation("SubscriptionTokensSpent");
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenTransactionPurchasedTokenPack", b =>
                {
                    b.HasOne("Laraue.Apps.Billing.DataAccess.Entities.PurchasedTokenPack", "PurchasedTokenPack")
                        .WithMany()
                        .HasForeignKey("PurchasedTokenPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_transaction_purchased_token_packs_purchased_token_pac");

                    b.HasOne("Laraue.Apps.Billing.DataAccess.Entities.TokenTransaction", null)
                        .WithMany("PurchasedTokensSpent")
                        .HasForeignKey("TokenTransactionId")
                        .HasConstraintName("fk_token_transaction_purchased_token_packs_token_transactions_");

                    b.Navigation("PurchasedTokenPack");
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenTransactionSubscriptionTokenPack", b =>
                {
                    b.HasOne("Laraue.Apps.Billing.DataAccess.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_transaction_subscription_token_packs_subscriptions_su");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Laraue.Apps.Billing.DataAccess.Entities.TokenTransaction", b =>
                {
                    b.Navigation("PurchasedTokensSpent");
                });
#pragma warning restore 612, 618
        }
    }
}
